seed:
  value: 42
lr:
  value: 0.0001
epochs:
  value: 50
batch_size:
  value: 64
val_batch_size:
  value: 16
optimizer:
  value: "Adam"
resize:
  value: [384, 384]
criterion:
  value: 'cross_entropy'
model:
  value: 'Resnet50'
early_stop:
  value: 10
val_ratio:
  value: 0.2
log_interval:
  value: 1
dataset:
  value: 'Fish_Dataset'
transform:
  value: 'Basepreprocessing'
model_dir:
  desc: 'output이 저장될 경로'
  value: '/opt/ml/final-project-level3-cv-13/ml/output'
output_folder_name:
  desc: 'output에 생성될 폴더 이름'
  value: 'exp'
data_dir:
  desc: 'data 저장소 경로'
  value: '/opt/ml/final-project-level3-cv-13/Data_prepare/Fish_dataset/output/crop_image'
ann_dir:
  desc: 'csv 저장소 경로'
  value: '/opt/ml/final-project-level3-cv-13/Data_prepare/Fish_dataset/output/analysis_csv'

