seed:
  value: 42
fish_classes:
  value: {'Olive_flounder' : '광어',
          'Korea_rockfish' : '우럭',
          'Red_seabream' : '참돔',
          'Black_porgy' : '감성돔',
          'Rock_bream' : '돌돔',
          'Croaker' : '민어',
          'Argyrosomus_japonicus' : '큰민어',
          'Starry_flounder' : '강도다리',
          'Longtooth_grouper' : '자바리',
          'Convict_grouper' : '능성어',
          'Japanese_amberjack' : '방어',
          'Yellowtail_amberjack' : '부시리',
          }
sashimi_classes:
  value: {'Olive_flounder_sashimi' : '광어회',
          'Korea_rockfish_sashimi' : '우럭회',
          'Red_seabream_sashimi' : '참돔회',
          'Brown_croaker_sashimi' : '민어회',
          'Red_drum_sashimi' : '점성어회',
          'Tilapia_sashimi' : '틸라피아회',
          'Salmon_sashimi' : '연어회',
          'Tuna_sashimi' : '참치회',
          'Japanese_amberjack_sashimi' : '방어회'
          }
lr:
  value: 0.0001
epochs:
  value: 10
batch_size:
  value: 64
val_batch_size:
  value: 16
optimizer:
  desc: 'SGD, Momentum, Adam, AdamW, Adagrad'
  value: "Adam"
resize:
  value: [384, 384]
criterion:
  value: 'cross_entropy'
model:
  value: 'EfficientNetB0'
scheduler:
  desc: 'step_lr, lambda_lr, multistep_lr, exponential_lr, cosine_annealing_lr, cosine_annealing_warm_restarts_lr, reduce_on_plateau_lr, cyclic_lr'
  value: 'cosine_annealing_warm_restarts_lr'
T_0:
  value: 50
early_stop:
  value: 5
val_ratio:
  value: 0.2
log_interval:
  value: 1
dataset:
  value: 'Fish_Dataset'
transform:
  value: 'transforms_1'
model_dir:
  desc: 'output이 저장될 경로'
  value: '../output'
output_folder_name:
  desc: 'output에 생성될 폴더 이름'
  value: 'exp'
data_dir:
  desc: 'data 저장소 경로'
  value: '../../../data/fish'
ann_dir:
  desc: 'csv 저장소 경로'
  value: '../../../data/fish'
momentum:
  value: 0.001
