method: random
metric:
  goal: maximize
  name: Val/best f1 score
parameters:
  batch_size:
    values:
      - 8
      - 16
      - 32
      - 64
  criterion:
    values:
      - cross_entropy
      - focal
      - label_smoothing
      - f1
  dataset:
    values:
      - Fish_Dataset
      - Sashimi_Dataset
  early_stop:
    value: 10
  epochs:
    distribution: int_uniform
    max: 200
    min: 150
  kfold:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
  lr:
    distribution: uniform
    max: 0.0002
    min: 5e-05
  model:
    distribution: categorical
    values:
      - Resnet50
      - EfficientNetB0
      - EfficientNetB4
      - EfficientNetB7
      - efficientnetv2_s
      - efficientnetv2_l
  name:
    distribution: categorical
    values:
      - exp
  optimizer:
    values:
      - Adam
      - AdamW
      - Adagrad
  scheduler:
    values:
      - step_lr
      - lambda_lr
      - multistep_lr
      - exponential_lr
      - cosine_annealing_lr
      - cosine_annealing_warm_restarts_lr
  transform:
    distribution: categorical
    values:
      - transforms_2
      - transforms_3
      - transforms_4
program: train.py